before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s
      - -w

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      android: Android
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
    files:
      - completions/*
      - README.md
      - LICENSE

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  groups:
    - title: Dependency updates
      regexp: "^.*feat\\(deps\\)*:+.*$"
      order: 300
    - title: 'New Features'
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 100
    - title: 'Bug fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 200
    - title: 'Documentation updates'
      regexp: "^.*docs[(\\w)]*:+.*$"
      order: 400
    - title: Other work
      order: 9999
  filters:
    exclude:
      - '^test'
      - '^chore'
      - '^refactor'
      - '^build'
      - 'merge conflict'
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
      - go mod tidy

release:
  github:
    owner: Inno-Gang
    name: goodle-cli

  name_template: "{{.ProjectName}} v{{.Version}}"
  header: |
    ## What's new?

  footer: |

    **Full Changelog**: https://github.com/Inno-Gang/goodle-cli/compare/{{ .PreviousTag }}...{{ .Tag }}

    ---



    Bugs? Suggestions? [Open an issue](https://github.com/Inno-Gang/goodle-cli/issues/new)

nfpms:
  - file_name_template: "{{ .ConventionalFileName }}"
    homepage: https://github.com/Inno-Gang/goodle-cli
    maintainer: metafates <fates@duck.com>
    description: |-
      A good way to access Moodle.

    license: MIT
    formats:
      - deb
      - rpm

    bindir: /usr/local/bin
    section: utils

    deb:
      lintian_overrides:
        - statically-linked-binary
        - changelog-file-missing-in-native-package

    contents:
      - src: ./completions/goodle-cli.bash
        dst: /usr/share/bash-completion/completions/goodle-cli
        file_info:
          mode: 0644
      - src: ./completions/goodle-cli.fish
        dst: /usr/share/fish/completions/goodle-cli.fish
        file_info:
          mode: 0644
      - src: ./completions/goodle-cli.zsh
        dst: /usr/share/zsh/vendor-completions/_goodle-cli
        file_info:
          mode: 0644
      - src: ./LICENSE
        dst: /usr/share/doc/goodle-cli/copyright
        file_info:
          mode: 0644