name: goreleaser

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  # packages: write
  # issues: write

jobs:
  goreleaser:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Fetch all tags
        run: git fetch --force --tags

      - name: Set up Go
        uses: actions/setup-go@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Generate Release Notes
        run: python ./.github/scripts/generate-release-notes.py # outputs a file named "changelog-temp.md"

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist --release-notes changelog-temp.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}