name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]

    env:
      GOFLAGS: -mod=readonly

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4

      - name: Test
        run: go test -race -v ./...
        if: runner.os != 'Windows'

      - name: Test (without race detector)
        run: go test -v ./...
        if: runner.os == 'Windows'
